<!-- Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. · https://www.zhuatech.cn/ -->
<script setup>
import { onMounted, ref } from 'vue'; import { getInventory } from '../../api/wms'
const list=ref([]); onMounted(async()=>list.value=await getInventory())
</script>
<template><div><div class="page-head"><div><h1>库存中心</h1><p>库存余额、批次状态与库位占用的一体化视图</p></div><div class="page-actions"><button class="btn">冻结 / 解冻</button><button class="btn">库存导出</button><button class="btn primary">发起盘点</button></div></div>
<section class="report-row"><article class="report-card"><span>库存 SKU</span><strong>3,286</strong><small>较上周增加 42</small></article><article class="report-card"><span>可用库存</span><strong>10.82 万</strong><small>已分配 1.86 万件</small></article><article class="report-card"><span>待上架库存</span><strong>336</strong><small>3 个收货暂存位</small></article><article class="report-card"><span>异常库存</span><strong>3</strong><small>1 项质检冻结</small></article></section>
<div class="filters"><input class="filter-input" placeholder="搜索 SKU、商品、库位或批次"><select class="filter-select"><option>全部库区</option><option>A 区</option><option>B 区</option></select><select class="filter-select"><option>全部质量状态</option><option>合格</option><option>冻结</option></select><span class="filter-spacer"></span><span class="result-count">当前展示 {{list.length}} 条库存明细</span></div>
<table class="data-table"><thead><tr><th>SKU / 商品</th><th>库区</th><th>库位</th><th>批次</th><th>可用</th><th>已分配</th><th>待上架</th><th>质量状态</th><th>最近盘点</th></tr></thead><tbody><tr v-for="i in list" :key="i.skuCode+i.locationCode"><td><strong>{{i.productName}}</strong><small>{{i.skuCode}}</small></td><td>{{i.zoneCode}}</td><td class="mono">{{i.locationCode}}</td><td class="mono">{{i.batchNo}}</td><td><strong>{{i.availableQty}} {{i.unit}}</strong></td><td>{{i.allocatedQty}} {{i.unit}}</td><td>{{i.inboundQty}} {{i.unit}}</td><td><span class="status" :class="i.qualityStatus==='HOLD'?'red':'green'">{{i.qualityStatus==='HOLD'?'冻结待复核':'合格'}}</span></td><td>{{i.lastCountAt.slice(5,16).replace('T',' ')}}</td></tr></tbody></table><div class="pager"><button>‹</button><button class="active">1</button><button>2</button><button>3</button><button>›</button></div></div></template>
