<!-- Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd. -->
<script setup>
import { onMounted, ref } from 'vue'; import { getInbounds } from '../../api/wms'
const list = ref([]); const statusName={RECEIVING:'收货中',ARRIVED:'已到仓',QC_HOLD:'质检待定'}; const statusClass=(v)=>v==='QC_HOLD'?'red':v==='RECEIVING'?'amber':'green'
onMounted(async()=>list.value=await getInbounds())
</script>
<template><div><div class="page-head"><div><h1>入库管理</h1><p>预约、到仓、收货和质检全过程协同</p></div><div class="page-actions"><button class="btn">导入 ASN</button><button class="btn primary">新建入库单</button></div></div>
<section class="report-row"><article class="report-card"><span>今日预约</span><strong>18</strong><small>6 车次已到仓</small></article><article class="report-card"><span>待卸货</span><strong>4</strong><small>平均等待 16 分钟</small></article><article class="report-card"><span>收货进行中</span><strong>7</strong><small>已收 806 / 1,168 件</small></article><article class="report-card"><span>质检待处理</span><strong>2</strong><small>含 1 项退货入库</small></article></section>
<div class="filters"><input class="filter-input" placeholder="搜索入库单号或供应商"><select class="filter-select"><option>全部状态</option><option>已预约</option><option>收货中</option></select><select class="filter-select"><option>全部月台</option><option>DOCK-01</option><option>DOCK-02</option></select><span class="filter-spacer"></span><span class="result-count">共 {{ list.length }} 条业务记录</span></div>
<table class="data-table"><thead><tr><th>入库单号</th><th>来源 / 供应商</th><th>预约时间</th><th>月台</th><th>行数</th><th>收货进度</th><th>操作员</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="i in list" :key="i.receiptNo"><td class="mono"><strong>{{i.receiptNo}}</strong></td><td><strong>{{i.supplierName}}</strong><small>{{i.sourceType}}</small></td><td>{{i.appointmentAt.slice(5,16).replace('T',' ')}}</td><td class="mono">{{i.dockCode}}</td><td>{{i.lineCount}} 行</td><td><div class="progress-track"><i :style="{width:`${i.receivedQty/i.plannedQty*100}%`}"></i></div><small>{{i.receivedQty}} / {{i.plannedQty}} 件</small></td><td>{{i.operatorName}}</td><td><span class="status" :class="statusClass(i.status)">{{statusName[i.status]}}</span></td><td><button class="btn">查看</button></td></tr></tbody></table><div class="pager"><button>‹</button><button class="active">1</button><button>2</button><button>›</button></div></div></template>
