# Copyright 2026 Shanghai Rujing Zhihua Information Technology Co., Ltd.
FROM node:24-alpine AS build
WORKDIR /workspace
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.29-alpine
LABEL org.opencontainers.image.vendor="上海如静知华信息科技有限公司"
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /workspace/dist /usr/share/nginx/html
EXPOSE 80

